let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
set number          
set relativenumber 

set termguicolors
syntax on
colorscheme gotham

let g:mapleader = ' '
nnoremap <leader>hd :Gvdiffsplit<CR>
set fillchars=diff:╱

