set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

set -g prefix C-w
unbind C-b
bind-key C-w send-prefix

unbind %
bind v split-window -h

unbind '"'
bind h split-window -v

unbind r
bind r source-file ~/.tmux.conf

bind -r m resize-pane -Z

set -g mouse on

# Vim settings

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"

unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode after dragging with mouse

# color scheme
set -g status-style bg='#1f1f29',fg='#957fb8'
setw -g window-status-current-style default

# fix warning: `focus-events` is not enabled. |'autoread'| may not work. 
set-option -g focus-events on

# Plugin
set -g @plugin 'tmux-plugins/tpm'

# list of tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator' # for navigating panes and vim/nvim with Ctrl-hjkl

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
